# Generated by Django 4.2 on 2023-11-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniportaluser",
            name="isVerified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alumniportaluser",
            name="signInMethod",
            field=models.CharField(
                blank=True,
                choices=[("google", "google"), ("email", "email")],
                max_length=255,
                null=True,
            ),
        ),
    ]
