# Generated by Django 4.2.7 on 2023-11-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alumniportaluser_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superadmin",
            options={
                "managed": True,
                "verbose_name": "Super Admin",
                "verbose_name_plural": "Super Admins",
            },
        ),
        migrations.CreateModel(
            name="Blogger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blogger",
                "verbose_name_plural": "Bloggers",
                "db_table": "blogger",
                "managed": True,
            },
        ),
    ]
