# Generated by Django 4.2 on 2023-11-10 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_superadmin_student_faculty_alumni"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alumniportaluser",
            old_name="identifer",
            new_name="identifier",
        ),
    ]
