# Generated by Django 4.2.7 on 2023-11-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alumniportaluser_isverified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="superadmin",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
    ]
