# Generated by Django 4.2.7 on 2023-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_superadmin_options_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniportaluser',
            name='privilege',
            field=models.CharField(blank=True, choices=[('Student', 'Super Admin'), ('Student', 'Staff'), ('Student', 'Alumni'), ('Student', 'Student')], max_length=255, null=True),
        ),
    ]
