# Generated by Django 4.2 on 2023-11-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("csc", "0001_initial"),
        ("users", "0003_rename_identifer_alumniportaluser_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumniportaluser",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="csc.city",
            ),
        ),
        migrations.AlterField(
            model_name="alumniportaluser",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Computer Engineering"),
                    ("2", "Mechanical Engineering"),
                    ("3", "Electronics & Telecommunication Engineering"),
                    ("4", "Electrical Engineering"),
                    ("5", "Information Technology"),
                    ("6", "Artificial Intelligence & Data Science"),
                    ("7", "First Year Engineering"),
                    ("8", "MBA"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="alumniportaluser",
            name="identifier",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="alumniportaluser",
            name="privilege",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Super Admin"),
                    ("2", "Staff"),
                    ("3", "Alumni"),
                    ("4", "Student"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
