# Generated by Django 4.2.7 on 2023-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_alumniportaluser_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniportaluser',
            name='privilege',
            field=models.CharField(blank=True, choices=[('Super Admin', 'Super Admin'), ('Staff', 'Staff'), ('Alumni', 'Alumni'), ('Student', 'Student')], max_length=255, null=True),
        ),
    ]
