# Generated by Django 4.2.7 on 2023-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_alumniportaluser_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniportaluser',
            name='isVerified',
            field=models.BooleanField(default=True),
        ),
    ]
