# Generated by Django 4.2.7 on 2023-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_alumniportaluser_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniportaluser',
            name='profilePicture',
            field=models.URLField(blank=True, default='https://img.icons8.com/fluency-systems-regular/96/user--v1.png', max_length=255, null=True),
        ),
    ]
