# Generated by Django 4.2.7 on 2023-12-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_alumniportaluser_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniportaluser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
