# Generated by Django 4.2.7 on 2023-11-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("amount", models.IntegerField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("1", "Computer Engineering"),
                            ("2", "Mechanical Engineering"),
                            ("3", "Electronics & Telecommunication Engineering"),
                            ("4", "Electrical Engineering"),
                            ("5", "Information Technology"),
                            ("6", "Artificial Intelligence & Data Science"),
                            ("7", "First Year Engineering"),
                            ("8", "MBA"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
