# Generated by Django 4.2 on 2023-11-10 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0002_alter_donation_options_alter_donation_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={"managed": True, "verbose_name_plural": "donations"},
        ),
    ]
