version: "3.1"
name: code-dev
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "alumni-portal-backend"
    user: "1000:1000"
    environment:
      ENV: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/:Z
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: "alumni-portal-db"
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - alumni-portal-db:/var/lib/postgresql/data

  pgadmin:
    container_name: "alumni-portal-pgadmin"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - alumni-portal-pgadmin:/var/lib/pgadmin

volumes:
  alumni-portal-pgadmin:
  alumni-portal-db:
