# Generated by Django 4.2.7 on 2023-12-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalytics',
            name='analyticsType',
            field=models.CharField(choices=[('profile visit', 'profile visit'), ('feed like', 'feed like'), ('feed comment', 'feed comment'), ('feed share', 'feed share')], default='profile visit', max_length=50),
        ),
    ]
