# Generated by Django 4.2.7 on 2023-12-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_useranalytics_analyticstype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranalytics',
            name='visitCount',
        ),
        migrations.AlterField(
            model_name='useranalytics',
            name='analyticsType',
            field=models.CharField(choices=[('profile visit', 'profile visit'), ('feed like', 'feed like'), ('feed comment', 'feed comment'), ('feed share', 'feed share'), ('connection', 'connection')], default='profile visit', max_length=50),
        ),
    ]
