# Generated by Django 4.2.7 on 2023-12-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
                ('notificationType', models.CharField(choices=[('EVENT', 'EVENT'), ('CONNECTION_REQUEST', 'CONNECTION_REQUEST'), ('CONNECTION_ACCEPTED', 'CONNECTION_ACCEPTED'), ('OPPORTUNITY', 'OPPORTUNITY'), ('LIKE', 'LIKE'), ('COMMENT', 'COMMENT')], max_length=100)),
                ('isRead', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-createdAt'],
                'managed': True,
            },
        ),
    ]
