# Generated by Django 4.2.7 on 2023-12-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notificationType',
            field=models.CharField(choices=[('EVENT', 'EVENT'), ('CONNECTION_REQUEST', 'CONNECTION_REQUEST'), ('CONNECTION_ACCEPTED', 'CONNECTION_ACCEPTED'), ('OPPORTUNITY_APPLICATION', 'OPPORTUNITY_APPLICATION'), ('OPPORTUNITY_APPLICATION_ACCEPTED', 'OPPORTUNITY_APPLICATION_ACCEPTED'), ('OPPORTUNITY_APPLICATION_REJECTED', 'OPPORTUNITY_APPLICATION_REJECTED'), ('LIKE', 'LIKE'), ('COMMENT', 'COMMENT')], max_length=100),
        ),
    ]
