# Generated by Django 4.2 on 2023-11-10 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0004_alter_alumniportaluser_city_and_more"),
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Job", "Job"),
                            ("Internship", "Internship"),
                            ("Scholarship", "Scholarship"),
                            ("Consultancy", "Consultancy"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("companyName", models.CharField(max_length=100)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("location", models.CharField(max_length=100)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="users.alumni",
                    ),
                ),
            ],
            options={
                "db_table": "opportunity",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="OpportunitySkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_skills",
                        to="opportunity.opportunity",
                    ),
                ),
                (
                    "skills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_skills_list",
                        to="skill.skill",
                    ),
                ),
            ],
            options={
                "db_table": "opportunity_skill",
                "ordering": ["-createdAt"],
            },
        ),
    ]
