# Generated by Django 4.2.7 on 2023-12-24 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill', '0002_alter_userskill_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('payPerMonth', models.IntegerField(blank=True, null=True)),
                ('isPaid', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship'), ('Scholarship', 'Scholarship'), ('Consultancy', 'Consultancy'), ('Other', 'Other')], max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('workMode', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('In Office', 'In Office'), ('Hybrid', 'Hybrid')], default='Hybrid', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunity',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='opportunity.opportunity')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='skill.skill')),
            ],
            options={
                'verbose_name': 'Opportunity Skill',
                'verbose_name_plural': 'Opportunity Skills',
                'db_table': 'opportunity_skill',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('about', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Application',
                'verbose_name_plural': 'Opportunity Applications',
                'db_table': 'opportunity_application',
                'ordering': ['-createdAt'],
            },
        ),
    ]
