# Generated by Django 4.2.7 on 2023-11-14 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alumniportaluser_bio"),
        ("opportunity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("isActive", models.BooleanField(default=True)),
                ("about", models.TextField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_applications",
                        to="users.alumni",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="opportunity.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Application",
                "verbose_name_plural": "Opportunity Applications",
                "db_table": "opportunity_application",
                "ordering": ["-createdAt"],
            },
        ),
    ]
