# Generated by Django 4.2.7 on 2023-11-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0002_opportunityapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                ],
                default="PENDING",
                max_length=100,
            ),
        ),
    ]
