# Generated by Django 4.2.7 on 2023-11-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0003_opportunityapplication_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="locationType",
        ),
        migrations.AddField(
            model_name="opportunity",
            name="isPaid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="payPerMonth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="workMode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remote", "Remote"),
                    ("In Office", "In Office"),
                    ("Hybrid", "Hybrid"),
                ],
                default="Hybrid",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="endDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="startDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
