# Generated by Django 4.2.7 on 2023-12-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.URLField(db_column='image', null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(db_column='keywords', max_length=200, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_column='title', max_length=200, verbose_name='Title'),
        ),
    ]
