# Generated by Django 4.2.7 on 2023-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image_blog_keywords_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogaction',
            name='action',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike'), ('report', 'report')], db_column='action', max_length=10, verbose_name='Action'),
        ),
    ]
