# Generated by Django 4.2.7 on 2023-11-27 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blogcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogaction',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_blog_actions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
