# Generated by Django 4.2.7 on 2023-11-11 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("isActive", models.BooleanField(default=True)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("venue", models.TextField()),
                (
                    "department",
                    models.TextField(
                        choices=[
                            ("1", "Computer Engineering"),
                            ("2", "Mechanical Engineering"),
                            ("3", "Electronics & Telecommunication Engineering"),
                            ("4", "Electrical Engineering"),
                            ("5", "Information Technology"),
                            ("6", "Artificial Intelligence & Data Science"),
                            ("7", "First Year Engineering"),
                            ("8", "MBA"),
                        ]
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "createdByUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="createdEvents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "event",
                "ordering": ["-createdAt"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("isActive", models.BooleanField(default=True)),
                ("image", models.URLField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Image",
                "verbose_name_plural": "Event Image",
                "db_table": "event_image",
                "ordering": ["-createdAt"],
                "managed": True,
            },
        ),
    ]
