# Generated by Django 4.2.7 on 2023-12-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_clubmember_user'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='club.club'),
        ),
        migrations.AddField(
            model_name='event',
            name='isClubEvent',
            field=models.BooleanField(default=False),
        ),
    ]
