# Generated by Django 4.2.7 on 2023-11-11 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_column="name", max_length=100, verbose_name="Name"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_column="name", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        db_column="country",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csc.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "States",
                "db_table": "state",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_column="name", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        db_column="state",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csc.state",
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "db_table": "city",
            },
        ),
    ]
