# Generated by Django 4.2 on 2023-11-10 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("csc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="city",
            table="city",
        ),
        migrations.AlterModelTable(
            name="country",
            table="country",
        ),
        migrations.AlterModelTable(
            name="state",
            table="state",
        ),
    ]
