# Generated by Django 4.2.7 on 2023-12-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_column='name', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
