# Generated by Django 4.2.7 on 2023-11-11 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=100, verbose_name="Subject")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed",
                "verbose_name_plural": "Feed",
                "db_table": "feed",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="FeedAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LIKE", "Like"),
                            ("SHARE", "Share"),
                            ("COMMENT", "Comment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="feed.feed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Action",
                "verbose_name_plural": "Feed Actions",
                "db_table": "feed_action",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="FeedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("image", models.URLField()),
                ("coverImage", models.BooleanField(default=False)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="feed.feed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Image",
                "verbose_name_plural": "Feed Images",
                "db_table": "feed_image",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="FeedActionComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "feed_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="feed.feedaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feed Action Comment",
                "verbose_name_plural": "Feed Action Comments",
                "db_table": "feed_action_comment",
                "ordering": ["-createdAt"],
            },
        ),
    ]
