# Generated by Django 4.2.7 on 2023-11-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedactioncomment",
            old_name="feed_action",
            new_name="feedAction",
        ),
    ]
