# Generated by Django 4.2.7 on 2023-11-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_rename_feed_action_feedactioncomment_feedaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="isPublic",
            field=models.BooleanField(default=True, verbose_name="Is Public"),
        ),
    ]
