# Generated by Django 4.2.7 on 2023-11-10 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connection",
            options={"managed": True, "verbose_name_plural": "connection"},
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("userA", "userB")},
        ),
        migrations.AlterModelTable(
            name="connection",
            table="connection",
        ),
    ]
