# Generated by Django 4.2.7 on 2023-12-26 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'managed': True, 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('user', 'company', 'designation', 'startDate', 'endDate', 'isCurrent')},
        ),
    ]
