# Generated by Django 4.2.7 on 2023-12-26 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
                ('website', models.URLField(null=True)),
                ('socialMedia1', models.URLField(null=True)),
                ('socialMedia2', models.URLField(null=True)),
                ('socialMedia3', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'club',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('faculty_mentor', 'faculty_mentor'), ('head', 'head'), ('core_member', 'core_member'), ('member', 'member')], max_length=100)),
                ('positionInWords', models.CharField(max_length=100)),
                ('isClubAdmin', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club Member',
                'verbose_name_plural': 'Club Members',
                'db_table': 'club_member',
                'managed': True,
                'unique_together': {('user', 'club')},
            },
        ),
    ]
