# Generated by Django 4.2.7 on 2023-12-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_clubmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='socialMedia1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='socialMedia2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='socialMedia3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
