# Generated by Django 4.2.7 on 2023-12-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='experience',
            field=models.CharField(choices=[('1', 'Interested'), ('2', 'Beginner'), ('3', 'Intermediate'), ('4', 'Expert'), ('5', 'Gawd')], max_length=100),
        ),
    ]
