# Generated by Django 4.2.7 on 2023-12-25 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill', '0002_alter_userskill_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'managed': True, 'ordering': ['-createdAt'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'managed': True, 'ordering': ['-createdAt'], 'verbose_name': 'User Skill', 'verbose_name_plural': 'User Skills'},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
    ]
